<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="priority test"
           tests="2"
           failures="1"
           errors="0"
           skipped="1"
           time="0.023">
    <properties></properties>

            <testcase
                name="testTwo"
                time="0.023"
                classname="pTest">

            <failure type="java.lang.AssertionError" message="expected [3] but found [2]">
                <![CDATA[java.lang.AssertionError: expected [3] but found [2]
                org.testng.Assert.fail(Assert.java:110)org.testng.Assert.failNotEquals(Assert.java:1577)org.testng.Assert.assertEqualsImpl(Assert.java:149)org.testng.Assert.assertEquals(Assert.java:131)org.testng.Assert.assertEquals(Assert.java:1418)org.testng.Assert.assertEquals(Assert.java:1382)org.testng.Assert.assertEquals(Assert.java:1428)pTest.testTwo(pTest.java:29)java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)java.base/java.lang.reflect.Method.invoke(Method.java:567)org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)java.base/java.lang.Thread.run(Thread.java:831)
]]>
            </failure>
    </testcase>

            <testcase
                name="testOne"
                time="0.0"
                classname="pTest">
            </testcase>

</testsuite>
